### ISSUE TITLE
Emulator Not works

### ISSUE THREAD

**Issue by mayweather911** [AnonymusRaccoon/ComSquare#54]
Hi Guys, I compiled lemulator and any game I tried doesn't work

**Comment by zoriya** [comment]
Yes, we know. Implementing an emulator is pretty hard, and we halted the development of the project. We may start it again someday, but with the current code we could run a simple tic-tac-toe game. You won't be able to run other games with this yet.

If you seek a working emulator, please try bsnes or mesen-s.
